### ISSUE TITLE
Notizen von Sprechstundeninhalten

### ISSUE THREAD

**Issue by dejo111** [UniRegensburg/ASE_WS1718-sprechstundenverwaltung#19]
Als Dozent möchte ich während oder nach dem Termin textuelle Notizen über Inhalte der Sprechstunde machen können, um in künftigen Terminen mit der Person zu wissen was bereits besprochen wurde. 

#40

**Comment by RVoelkel** [comment]
Notizen werden zusammen mit der Termin-ID gespeichert; evtl. Flag, bei welchen Terminen Notizen gemacht wurden.
