### ISSUE TITLE
Student: Beschreibung zu Terminbuchung

### ISSUE THREAD

**Issue by dejo111** [UniRegensburg/ASE_WS1718-sprechstundenverwaltung#21]
Als Student möchte ich für einen gebuchten Termin eine kurze Beschreibung angeben, um dem Dozenten eine ausführlichere Beschreibung als Vorbereitung für den Termin bieten zu können.

#40

**Comment by RVoelkel** [comment]
funktioniert im Frontend - todo: Backend!
